// Generated by Haxe 3.4.2
(function () { "use strict";
var test_commands_SomeOtherDummyTest = function() { };
test_commands_SomeOtherDummyTest.main = function() {
	test_support_Ava("Foobar",function(t) {
		t["is"]();
	});
	test_support_Ava("Foobar2",function(t1) {
		t1["true"](true);
	});
};
var test_support_Ava = require("ava");
test_commands_SomeOtherDummyTest.main();
})();
